package ec.edu.epn.doctorfit.sqlite.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import ec.edu.epn.doctorfit.sqlite.db.AlimentacionSedentarismo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALIMENTACION_SEDENTARISMO".
*/
public class AlimentacionSedentarismoDao extends AbstractDao<AlimentacionSedentarismo, Long> {

    public static final String TABLENAME = "ALIMENTACION_SEDENTARISMO";

    /**
     * Properties of entity AlimentacionSedentarismo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Calorias = new Property(1, float.class, "calorias", false, "CALORIAS");
        public final static Property Grasas = new Property(2, float.class, "grasas", false, "GRASAS");
        public final static Property Proteinas = new Property(3, float.class, "proteinas", false, "PROTEINAS");
        public final static Property PorcentajeSedentarismo = new Property(4, float.class, "porcentajeSedentarismo", false, "PORCENTAJE_SEDENTARISMO");
        public final static Property IdUsuario = new Property(5, long.class, "idUsuario", false, "ID_USUARIO");
    };

    private DaoSession daoSession;

    private Query<AlimentacionSedentarismo> usuario_AlimentacionSedentarismoListQuery;

    public AlimentacionSedentarismoDao(DaoConfig config) {
        super(config);
    }
    
    public AlimentacionSedentarismoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALIMENTACION_SEDENTARISMO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CALORIAS\" REAL NOT NULL ," + // 1: calorias
                "\"GRASAS\" REAL NOT NULL ," + // 2: grasas
                "\"PROTEINAS\" REAL NOT NULL ," + // 3: proteinas
                "\"PORCENTAJE_SEDENTARISMO\" REAL NOT NULL ," + // 4: porcentajeSedentarismo
                "\"ID_USUARIO\" INTEGER NOT NULL );"); // 5: idUsuario
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALIMENTACION_SEDENTARISMO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AlimentacionSedentarismo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getCalorias());
        stmt.bindDouble(3, entity.getGrasas());
        stmt.bindDouble(4, entity.getProteinas());
        stmt.bindDouble(5, entity.getPorcentajeSedentarismo());
        stmt.bindLong(6, entity.getIdUsuario());
    }

    @Override
    protected void attachEntity(AlimentacionSedentarismo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AlimentacionSedentarismo readEntity(Cursor cursor, int offset) {
        AlimentacionSedentarismo entity = new AlimentacionSedentarismo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getFloat(offset + 1), // calorias
            cursor.getFloat(offset + 2), // grasas
            cursor.getFloat(offset + 3), // proteinas
            cursor.getFloat(offset + 4), // porcentajeSedentarismo
            cursor.getLong(offset + 5) // idUsuario
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AlimentacionSedentarismo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCalorias(cursor.getFloat(offset + 1));
        entity.setGrasas(cursor.getFloat(offset + 2));
        entity.setProteinas(cursor.getFloat(offset + 3));
        entity.setPorcentajeSedentarismo(cursor.getFloat(offset + 4));
        entity.setIdUsuario(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AlimentacionSedentarismo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AlimentacionSedentarismo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "alimentacionSedentarismoList" to-many relationship of Usuario. */
    public List<AlimentacionSedentarismo> _queryUsuario_AlimentacionSedentarismoList(long idUsuario) {
        synchronized (this) {
            if (usuario_AlimentacionSedentarismoListQuery == null) {
                QueryBuilder<AlimentacionSedentarismo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdUsuario.eq(null));
                usuario_AlimentacionSedentarismoListQuery = queryBuilder.build();
            }
        }
        Query<AlimentacionSedentarismo> query = usuario_AlimentacionSedentarismoListQuery.forCurrentThread();
        query.setParameter(0, idUsuario);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsuarioDao().getAllColumns());
            builder.append(" FROM ALIMENTACION_SEDENTARISMO T");
            builder.append(" LEFT JOIN USUARIO T0 ON T.\"ID_USUARIO\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AlimentacionSedentarismo loadCurrentDeep(Cursor cursor, boolean lock) {
        AlimentacionSedentarismo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Usuario usuario = loadCurrentOther(daoSession.getUsuarioDao(), cursor, offset);
         if(usuario != null) {
            entity.setUsuario(usuario);
        }

        return entity;    
    }

    public AlimentacionSedentarismo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AlimentacionSedentarismo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AlimentacionSedentarismo> list = new ArrayList<AlimentacionSedentarismo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AlimentacionSedentarismo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AlimentacionSedentarismo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
