package ec.edu.epn.doctorfit.sqlite.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONSEJO".
 */
public class Consejo {

    private Long id;
    /** Not-null value. */
    private String textoInformativo;

    public Consejo() {
    }

    public Consejo(Long id) {
        this.id = id;
    }

    public Consejo(Long id, String textoInformativo) {
        this.id = id;
        this.textoInformativo = textoInformativo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTextoInformativo() {
        return textoInformativo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTextoInformativo(String textoInformativo) {
        this.textoInformativo = textoInformativo;
    }

}
