package ec.edu.epn.doctorfit.sqlite.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import ec.edu.epn.doctorfit.sqlite.db.UsuarioDao;
import ec.edu.epn.doctorfit.sqlite.db.EstadoDao;
import ec.edu.epn.doctorfit.sqlite.db.EstadoDeseadoDao;
import ec.edu.epn.doctorfit.sqlite.db.AlimentacionSedentarismoDao;
import ec.edu.epn.doctorfit.sqlite.db.ConsejoDao;
import ec.edu.epn.doctorfit.sqlite.db.PlatilloDao;
import ec.edu.epn.doctorfit.sqlite.db.AlimentoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UsuarioDao.createTable(db, ifNotExists);
        EstadoDao.createTable(db, ifNotExists);
        EstadoDeseadoDao.createTable(db, ifNotExists);
        AlimentacionSedentarismoDao.createTable(db, ifNotExists);
        ConsejoDao.createTable(db, ifNotExists);
        PlatilloDao.createTable(db, ifNotExists);
        AlimentoDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UsuarioDao.dropTable(db, ifExists);
        EstadoDao.dropTable(db, ifExists);
        EstadoDeseadoDao.dropTable(db, ifExists);
        AlimentacionSedentarismoDao.dropTable(db, ifExists);
        ConsejoDao.dropTable(db, ifExists);
        PlatilloDao.dropTable(db, ifExists);
        AlimentoDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UsuarioDao.class);
        registerDaoClass(EstadoDao.class);
        registerDaoClass(EstadoDeseadoDao.class);
        registerDaoClass(AlimentacionSedentarismoDao.class);
        registerDaoClass(ConsejoDao.class);
        registerDaoClass(PlatilloDao.class);
        registerDaoClass(AlimentoDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
