package ec.edu.epn.doctorfit.sqlite.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import ec.edu.epn.doctorfit.sqlite.db.Dieta;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIETA".
*/
public class DietaDao extends AbstractDao<Dieta, Long> {

    public static final String TABLENAME = "DIETA";

    /**
     * Properties of entity Dieta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TipoDieta = new Property(1, String.class, "tipoDieta", false, "TIPO_DIETA");
        public final static Property IdEstadoDeseado = new Property(2, long.class, "idEstadoDeseado", false, "ID_ESTADO_DESEADO");
    };

    private DaoSession daoSession;

    private Query<Dieta> estadoDeseado_DietaListQuery;

    public DietaDao(DaoConfig config) {
        super(config);
    }
    
    public DietaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIETA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TIPO_DIETA\" TEXT NOT NULL ," + // 1: tipoDieta
                "\"ID_ESTADO_DESEADO\" INTEGER NOT NULL );"); // 2: idEstadoDeseado
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIETA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Dieta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTipoDieta());
        stmt.bindLong(3, entity.getIdEstadoDeseado());
    }

    @Override
    protected void attachEntity(Dieta entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Dieta readEntity(Cursor cursor, int offset) {
        Dieta entity = new Dieta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // tipoDieta
            cursor.getLong(offset + 2) // idEstadoDeseado
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Dieta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTipoDieta(cursor.getString(offset + 1));
        entity.setIdEstadoDeseado(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Dieta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Dieta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dietaList" to-many relationship of EstadoDeseado. */
    public List<Dieta> _queryEstadoDeseado_DietaList(long idEstadoDeseado) {
        synchronized (this) {
            if (estadoDeseado_DietaListQuery == null) {
                QueryBuilder<Dieta> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdEstadoDeseado.eq(null));
                estadoDeseado_DietaListQuery = queryBuilder.build();
            }
        }
        Query<Dieta> query = estadoDeseado_DietaListQuery.forCurrentThread();
        query.setParameter(0, idEstadoDeseado);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEstadoDeseadoDao().getAllColumns());
            builder.append(" FROM DIETA T");
            builder.append(" LEFT JOIN ESTADO_DESEADO T0 ON T.\"ID_ESTADO_DESEADO\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Dieta loadCurrentDeep(Cursor cursor, boolean lock) {
        Dieta entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        EstadoDeseado estadoDeseado = loadCurrentOther(daoSession.getEstadoDeseadoDao(), cursor, offset);
         if(estadoDeseado != null) {
            entity.setEstadoDeseado(estadoDeseado);
        }

        return entity;    
    }

    public Dieta loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Dieta> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Dieta> list = new ArrayList<Dieta>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Dieta> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Dieta> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
