package ec.edu.epn.doctorfit.sqlite.db;

import ec.edu.epn.doctorfit.sqlite.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ESTADO".
 */
public class Estado {

    private Long id;
    private float peso;
    private float longitudAbdominal;
    private float longitudCadera;
    /** Not-null value. */
    private java.util.Date fechaEstado;
    private long idUsuario;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EstadoDao myDao;

    private Usuario usuario;
    private Long usuario__resolvedKey;


    public Estado() {
    }

    public Estado(Long id) {
        this.id = id;
    }

    public Estado(Long id, float peso, float longitudAbdominal, float longitudCadera, java.util.Date fechaEstado, long idUsuario) {
        this.id = id;
        this.peso = peso;
        this.longitudAbdominal = longitudAbdominal;
        this.longitudCadera = longitudCadera;
        this.fechaEstado = fechaEstado;
        this.idUsuario = idUsuario;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEstadoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public float getPeso() {
        return peso;
    }

    public void setPeso(float peso) {
        this.peso = peso;
    }

    public float getLongitudAbdominal() {
        return longitudAbdominal;
    }

    public void setLongitudAbdominal(float longitudAbdominal) {
        this.longitudAbdominal = longitudAbdominal;
    }

    public float getLongitudCadera() {
        return longitudCadera;
    }

    public void setLongitudCadera(float longitudCadera) {
        this.longitudCadera = longitudCadera;
    }

    /** Not-null value. */
    public java.util.Date getFechaEstado() {
        return fechaEstado;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaEstado(java.util.Date fechaEstado) {
        this.fechaEstado = fechaEstado;
    }

    public long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

    /** To-one relationship, resolved on first access. */
    public Usuario getUsuario() {
        long __key = this.idUsuario;
        if (usuario__resolvedKey == null || !usuario__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UsuarioDao targetDao = daoSession.getUsuarioDao();
            Usuario usuarioNew = targetDao.load(__key);
            synchronized (this) {
                usuario = usuarioNew;
            	usuario__resolvedKey = __key;
            }
        }
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        if (usuario == null) {
            throw new DaoException("To-one property 'idUsuario' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.usuario = usuario;
            idUsuario = usuario.getId();
            usuario__resolvedKey = idUsuario;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
