package ec.edu.epn.doctorfit.sqlite.db;

import java.util.List;
import ec.edu.epn.doctorfit.sqlite.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLATILLO".
 */
public class Platillo {

    private Long id;
    /** Not-null value. */
    private String nombrePlatillo;
    private long idDieta;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient PlatilloDao myDao;

    private Dieta dieta;
    private Long dieta__resolvedKey;

    private List<Alimento> alimentoList;

    public Platillo() {
    }

    public Platillo(Long id) {
        this.id = id;
    }

    public Platillo(Long id, String nombrePlatillo, long idDieta) {
        this.id = id;
        this.nombrePlatillo = nombrePlatillo;
        this.idDieta = idDieta;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPlatilloDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombrePlatillo() {
        return nombrePlatillo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombrePlatillo(String nombrePlatillo) {
        this.nombrePlatillo = nombrePlatillo;
    }

    public long getIdDieta() {
        return idDieta;
    }

    public void setIdDieta(long idDieta) {
        this.idDieta = idDieta;
    }

    /** To-one relationship, resolved on first access. */
    public Dieta getDieta() {
        long __key = this.idDieta;
        if (dieta__resolvedKey == null || !dieta__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DietaDao targetDao = daoSession.getDietaDao();
            Dieta dietaNew = targetDao.load(__key);
            synchronized (this) {
                dieta = dietaNew;
            	dieta__resolvedKey = __key;
            }
        }
        return dieta;
    }

    public void setDieta(Dieta dieta) {
        if (dieta == null) {
            throw new DaoException("To-one property 'idDieta' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.dieta = dieta;
            idDieta = dieta.getId();
            dieta__resolvedKey = idDieta;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Alimento> getAlimentoList() {
        if (alimentoList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AlimentoDao targetDao = daoSession.getAlimentoDao();
            List<Alimento> alimentoListNew = targetDao._queryPlatillo_AlimentoList(id);
            synchronized (this) {
                if(alimentoList == null) {
                    alimentoList = alimentoListNew;
                }
            }
        }
        return alimentoList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetAlimentoList() {
        alimentoList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
