package ec.edu.epn.doctorfit.sqlite.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import ec.edu.epn.doctorfit.sqlite.db.Platillo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PLATILLO".
*/
public class PlatilloDao extends AbstractDao<Platillo, Long> {

    public static final String TABLENAME = "PLATILLO";

    /**
     * Properties of entity Platillo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NombrePlatillo = new Property(1, String.class, "nombrePlatillo", false, "NOMBRE_PLATILLO");
        public final static Property IdDieta = new Property(2, long.class, "idDieta", false, "ID_DIETA");
    };

    private DaoSession daoSession;

    private Query<Platillo> dieta_PlatilloListQuery;

    public PlatilloDao(DaoConfig config) {
        super(config);
    }
    
    public PlatilloDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PLATILLO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NOMBRE_PLATILLO\" TEXT NOT NULL ," + // 1: nombrePlatillo
                "\"ID_DIETA\" INTEGER NOT NULL );"); // 2: idDieta
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PLATILLO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Platillo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombrePlatillo());
        stmt.bindLong(3, entity.getIdDieta());
    }

    @Override
    protected void attachEntity(Platillo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Platillo readEntity(Cursor cursor, int offset) {
        Platillo entity = new Platillo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // nombrePlatillo
            cursor.getLong(offset + 2) // idDieta
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Platillo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombrePlatillo(cursor.getString(offset + 1));
        entity.setIdDieta(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Platillo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Platillo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "platilloList" to-many relationship of Dieta. */
    public List<Platillo> _queryDieta_PlatilloList(long idDieta) {
        synchronized (this) {
            if (dieta_PlatilloListQuery == null) {
                QueryBuilder<Platillo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdDieta.eq(null));
                dieta_PlatilloListQuery = queryBuilder.build();
            }
        }
        Query<Platillo> query = dieta_PlatilloListQuery.forCurrentThread();
        query.setParameter(0, idDieta);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDietaDao().getAllColumns());
            builder.append(" FROM PLATILLO T");
            builder.append(" LEFT JOIN DIETA T0 ON T.\"ID_DIETA\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Platillo loadCurrentDeep(Cursor cursor, boolean lock) {
        Platillo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Dieta dieta = loadCurrentOther(daoSession.getDietaDao(), cursor, offset);
         if(dieta != null) {
            entity.setDieta(dieta);
        }

        return entity;    
    }

    public Platillo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Platillo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Platillo> list = new ArrayList<Platillo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Platillo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Platillo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
